name: 📘 Markdown Quality Check

on:
    pull_request:
        paths:
            - "**/*.md"

jobs:
    markdown-check:
        name: 🔍 Lint, Link & Format Markdown
        runs-on: ubuntu-latest

        steps:
            - name: ⬇️ Checkout Code
              uses: actions/checkout@v3

            - name: ⚙️ Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: "npm"

            - name: 📦 Install Tools
              run: |
                  npm install -g markdownlint-cli2 markdown-link-check prettier

            - name: 🧹 Lint Markdown
              run: markdownlint-cli2 "**/*.md"

            - name: 🔗 Check Markdown Links
              run: |
                  find . -name "*.md" -print0 | xargs -0 -n1 markdown-link-check --quiet --retry

            - name: 🎨 Check Markdown Formatting
              run: prettier --check "**/*.md"
